spider_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
 
  camera_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: camera_joint
    pid: {p: 10.0, i: 1.0, d: 10.0}

